name: DocumentHosting

on: [push]

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      # Must be set to this for deploying to GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-12
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Build DocC
        run: |
          xcodebuild docbuild -scheme SwiftCppApp \
            -derivedDataPath /tmp/docbuild \
            -destination 'generic/platform=iOS';
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/SwiftCppApp.doccarchive \
            --hosting-base-path SwiftCppApp \
            --output-path docs;
          echo "<script>window.location.href += \"/documentation/swiftcppapp\"</script>" > docs/index.html;
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload only docs directory
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
